# Generated by Django 4.2.9 on 2024-01-10 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Product name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('stock', models.IntegerField(verbose_name='Products in stock')),
                ('description', models.TextField(verbose_name='Description')),
                ('picture', models.ImageField(upload_to='', verbose_name='Picture')),
                ('category', models.ForeignKey(default='no category', on_delete=django.db.models.deletion.SET_DEFAULT, to='products.productcategory', verbose_name='Category')),
            ],
        ),
    ]
