# Generated by Django 5.0.1 on 2024-01-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Picture'),
        ),
    ]
