# Generated by Django 5.0.1 on 2024-01-16 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.paymentmethod', verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.receipttype', verbose_name='Receipt'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.shippingmethod', verbose_name='Shipping'),
        ),
    ]
