# Generated by Django 5.0.1 on 2024-01-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='total',
            field=models.IntegerField(blank=True, null=True, verbose_name='total'),
        ),
    ]
