# Generated by Django 5.0.1 on 2024-01-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sales_payment_alter_sales_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
