# Generated by Django 5.0.1 on 2024-01-11 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producer_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productor',
            new_name='formulario',
        ),
    ]
