# Generated by Django 4.2.9 on 2024-01-15 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producer_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationform',
            name='producer_type',
        ),
    ]
