# Generated by Django 4.2.9 on 2024-01-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producer_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productor',
            new_name='formulario',
        ),
    ]
