# Generated by Django 4.2.9 on 2024-01-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer_application', '0002_remove_applicationform_producer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='application_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de postulación'),
        ),
    ]
