# Generated by Django 4.2.9 on 2024-01-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer_application', '0003_applicationform_application_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='application_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de postulación'),
        ),
    ]
