# Generated by Django 5.0.1 on 2024-01-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproducer',
            name='is_producer',
            field=models.BooleanField(default=True),
        ),
    ]
