# Generated by Django 4.2.9 on 2024-01-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclient',
            name='phonenumber',
            field=models.IntegerField(default=900000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userproducer',
            name='phonenumber',
            field=models.IntegerField(default=900000000),
            preserve_default=False,
        ),
    ]
