# Generated by Django 4.2.9 on 2024-01-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclient',
            name='is_producer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userproducer',
            name='is_producer',
            field=models.BooleanField(default=True),
        ),
    ]
