# Generated by Django 4.2.9 on 2024-01-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userclient_phonenumber_userproducer_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproducer',
            name='businessname',
            field=models.CharField(default='Negocio por defecto', max_length=100, verbose_name='Business Name'),
            preserve_default=False,
        ),
    ]
